

-----------------------------------------this is the logger of project , you can see the methods that calls and information of them  in here------------------------------------

Sun Sep 01 00:12:17 PDT 2019
exception message :Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
lines that exception occurred ===>
[com.dpco.business.dao.MemberDao.findByUsernameAndPassword(MemberDao.java:45)
 com.dpco.business.dao.MemberDao$$FastClassBySpringCGLIB$$b51b7b37.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$8450cca2.findByUsernameAndPassword(<generated>)
 com.dpco.business.service.MemberService.findByUsernameAndPassword(MemberService.java:20)
 com.dpco.business.security.JwtGenerator.generate(JwtGenerator.java:35)
 com.dpco.controller.LoginController.generate(LoginController.java:32)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$fab510c6.generate(<generated>)
-----------------------------------------------------------------------------------------
Sun Sep 01 00:15:16 PDT 2019
exception message :Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
lines that exception occurred ===>
[com.dpco.business.dao.MemberDao.findByUsernameAndPassword(MemberDao.java:45)
 com.dpco.business.dao.MemberDao$$FastClassBySpringCGLIB$$b51b7b37.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$3445b93e.findByUsernameAndPassword(<generated>)
 com.dpco.business.service.MemberService.findByUsernameAndPassword(MemberService.java:20)
 com.dpco.business.security.JwtGenerator.generate(JwtGenerator.java:35)
 com.dpco.controller.LoginController.generate(LoginController.java:32)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$ea7c8d74.generate(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 00:17:28 PDT 2019
exception message :Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]
lines that exception occurred ===>
[com.dpco.business.dao.MemberDao.findByUsernameAndPassword(MemberDao.java:45)
 com.dpco.business.dao.MemberDao$$FastClassBySpringCGLIB$$b51b7b37.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$7e30ee7.findByUsernameAndPassword(<generated>)
 com.dpco.business.service.MemberService.findByUsernameAndPassword(MemberService.java:20)
 com.dpco.business.security.JwtGenerator.generate(JwtGenerator.java:35)
 com.dpco.controller.LoginController.generate(LoginController.java:32)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$9640d40f.generate(<generated>)
-----------------------------------------------------------------------------------------

---------------------------------------save-------------------------------------------
path is : /save
the method of request is :POST
the arguments of this method is : om.dpco.business.entity.Member@46a0605,
the milli seconds that left : 20054
---------------------------------------save-------------------------------------------
path is : /save
the method of request is :POST
the arguments of this method is : om.dpco.business.entity.Member@2cd1e93f,
the milli seconds that left : 5577  EXCEPTION    

Sun Sep 01 00:45:13 PDT 2019
exception message :Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:36)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$b9f3c598.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:42)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$3539d7bf.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 00:48:56 PDT 2019
exception message :Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [com.dpco.business.entity.Member#2]
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:36)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$128bc480.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:42)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$1852f2e.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 00:49:27 PDT 2019
exception message :A different object with the same identifier value was already associated with the session : [com.dpco.business.entity.Member#1]
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:36)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$128bc480.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:42)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$1852f2e.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 00:53:47 PDT 2019
exception message :A different object with the same identifier value was already associated with the session : [com.dpco.business.entity.Member#1]
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:36)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$b7ddc24d.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:42)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$6d454593.save(<generated>)
-----------------------------------------------------------------------------------------

---------------------------------------save-------------------------------------------
path is : /save
the method of request is :POST
the arguments of this method is : om.dpco.business.entity.Member@38c7fded,
the milli seconds that left : 2135  EXCEPTION    

Sun Sep 01 00:59:08 PDT 2019
exception message :A different object with the same identifier value was already associated with the session : [com.dpco.business.entity.Member#1]
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:36)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$d24e0a82.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:42)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$d0bb10d5.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 01:01:37 PDT 2019
exception message :A different object with the same identifier value was already associated with the session : [com.dpco.business.entity.Member#1]
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:36)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$733a3a3e.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:42)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$da4c1f3f.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 01:04:25 PDT 2019
exception message :A different object with the same identifier value was already associated with the session : [com.dpco.business.entity.Member#1]
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:36)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$e3e76e02.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:42)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$4fb47961.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 01:09:09 PDT 2019
exception message :no transaction is in progress
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:38)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$ad4413b2.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:42)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$3e5d4529.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 01:09:52 PDT 2019
exception message :org.hibernate.exception.ConstraintViolationException: could not execute statement
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:38)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$ad4413b2.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:42)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$3e5d4529.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 01:10:23 PDT 2019
exception message :no transaction is in progress
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:38)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$ad4413b2.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:42)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$3e5d4529.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 01:11:51 PDT 2019
exception message :no transaction is in progress
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:37)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$20ed78a3.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:42)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$1de17e6a.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 01:13:40 PDT 2019
exception message :Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [com.dpco.business.entity.Member#2]
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:37)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$20ed78a3.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:42)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$1de17e6a.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 01:15:22 PDT 2019
exception message :A different object with the same identifier value was already associated with the session : [com.dpco.business.entity.Member#1]
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:37)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$5fc83398.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:42)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$917ccb95.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 01:17:43 PDT 2019
exception message :no transaction is in progress
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:37)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$b476246f.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:42)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$8fa8db.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 01:19:04 PDT 2019
exception message :no transaction is in progress
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:37)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$b476246f.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:42)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$8fa8db.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 02:41:28 PDT 2019
exception message :A different object with the same identifier value was already associated with the session : [com.dpco.business.entity.Member#1]
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:37)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$5dd40fe.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:43)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$29775276.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 02:43:44 PDT 2019
exception message :A different object with the same identifier value was already associated with the session : [com.dpco.business.entity.Member#1]
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:37)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$ed1e0ac3.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:43)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$ef7925fb.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 02:46:09 PDT 2019
exception message :Error accessing stax stream
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:37)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$4014bcbc.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:43)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$6e169fc2.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 02:48:33 PDT 2019
exception message :A different object with the same identifier value was already associated with the session : [com.dpco.business.entity.Member#1]
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:37)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$3402051b.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:43)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$157d8ac9.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 02:51:11 PDT 2019
exception message :no transaction is in progress
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:37)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$f885d73a.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:43)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$a43812fb.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 02:51:54 PDT 2019
exception message :A different object with the same identifier value was already associated with the session : [com.dpco.business.entity.Member#1]
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:37)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$f885d73a.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:43)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$a43812fb.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 02:53:13 PDT 2019
exception message :no transaction is in progress
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:37)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$7eb72200.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:43)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$eafe627.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 02:53:27 PDT 2019
exception message :no transaction is in progress
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:37)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$7eb72200.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:43)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$eafe627.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 02:53:45 PDT 2019
exception message :no transaction is in progress
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:37)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$7eb72200.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:43)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$eafe627.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 02:54:11 PDT 2019
exception message :no transaction is in progress
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:37)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$7eb72200.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:43)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$eafe627.save(<generated>)
-----------------------------------------------------------------------------------------
  EXCEPTION    

Sun Sep 01 02:55:25 PDT 2019
exception message :no transaction is in progress
lines that exception occurred ===>
[com.dpco.business.dao.GenericDao.save(GenericDao.java:37)
 com.dpco.business.dao.GenericDao$$FastClassBySpringCGLIB$$50ecf97c.invoke(<generated>)
 com.dpco.business.dao.MemberDao$$EnhancerBySpringCGLIB$$7eb72200.save(<generated>)
 com.dpco.business.service.GenericService.save(GenericService.java:25)
 com.dpco.controller.LoginController.save(LoginController.java:43)
 com.dpco.controller.LoginController$$FastClassBySpringCGLIB$$98399abc.invoke(<generated>)
 com.dpco.aop.LoggerAspect.around(LoggerAspect.java:56)
 com.dpco.controller.LoginController$$EnhancerBySpringCGLIB$$eafe627.save(<generated>)
-----------------------------------------------------------------------------------------

---------------------------------------save-------------------------------------------
path is : /save
the method of request is :POST
the arguments of this method is : om.dpco.business.entity.Member@655f817d,
the milli seconds that left : 13692
---------------------------------------save-------------------------------------------
path is : /save
the method of request is :POST
the arguments of this method is : om.dpco.business.entity.Member@6cdd8fb6,
the milli seconds that left : 2782
---------------------------------------save-------------------------------------------
path is : /save
the method of request is :POST
the arguments of this method is : om.dpco.business.entity.Member@4747541d,
the milli seconds that left : 2456
---------------------------------------save-------------------------------------------
path is : /save
the method of request is :POST
the arguments of this method is : om.dpco.business.entity.Member@4a396b2,
the milli seconds that left : 5022